export const dataAuth = [
  { id: 1, login: "Vlad", password: "123" },
  { id: 2, login: "Anna", password: "qwerty" },
  { id: 3, login: "Maxim", password: "password123" },
  { id: 4, login: "Elena", password: "elena2024" },
  { id: 5, login: "Sergey", password: "serg_pass" },
  { id: 6, login: "Olga", password: "olga_secure" },
  { id: 7, login: "Dmitry", password: "dima007" },
  { id: 8, login: "Irina", password: "irina88" },
  { id: 9, login: "Alex", password: "alexander" },
  { id: 10, login: "Maria", password: "masha123" },
  { id: 11, login: "Andrey", password: "andrey_pass" },
  { id: 12, login: "Kate", password: "kate2024" },
  { id: 13, login: "Pavel", password: "pavel_work" },
  { id: 14, login: "Svetlana", password: "sveta_light" },
  { id: 15, login: "Ivan", password: "ivan_ivanov" },
  { id: 16, login: "Tatiana", password: "tanya_pass" },
  { id: 17, login: "Nikolay", password: "kolya123" },
  { id: 18, login: "Julia", password: "yulia_j" },
  { id: 19, login: "Mikhail", password: "misha_m" },
  { id: 20, login: "Natalia", password: "nata2024" },
]
